services:
  - docker
before_install:
  - pip install --user awscli 
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region us-west-2
  - aws configure list 

after_success:
  - eval $(aws ecr get-login --no-include-email --region us-west-2)
  - docker build -t awselasticbean .
  - docker tag awselasticbean:latest 574137776403.dkr.ecr.us-west-2.amazonaws.com/shrigowri
  - docker push 574137776403.dkr.ecr.us-west-2.amazonaws.com/shrigowri
